name: Functional Tests

on:
  push:
    branches: [ "ActionTest" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECTS_PATH: /home/runner/work/CppQueryable

jobs:
  # linux:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Intall GTEST and GMOCK
  #     run: sudo apt-get install libgtest-dev && sudo apt-get install cmake && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp ./lib/*.a /usr/lib

  #   - uses: actions/checkout@v3
  #   - name: Build and Run Functional Tests
  #     run: make FuncTests

  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:

    # (not sure if this step is necessary since we're already in git hub)
    # - name: Set up MinGW
    #   uses: egor-tensin/setup-mingw@v2
    #   with:
    #     platform: x64
    
    - name: Install GTEST and GMOCK
      run: mkdir ./Installs && cd Installs && git clone https://github.com/google/googletest.git
    
    - name: Display Installs Directory
      run: cd ./Installs/googletest && ls -l && cmake CMakeLists.txt && cmake && ls -l
    
    - name: Add GTEST Output to PATH
      run: Add-Content $env:GITHUB_PATH "D:\a\CppQueryable\CppQueryable\Installs\googletest"
      shell: pwsh
      # run: echo "D:/a/CppQueryable/CppQueryable/Installs/googletest" >> $GITHUB_PATH && echo $GITHUB_PATH
    - name: Display the path
      run: echo ${env:GITHUB_PATH}
      shell: pwsh

    - uses: actions/checkout@v3
    - name: Build and Run Functional Tests
      run: make FuncTests