name: Functional Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECTS_PATH: /home/runner/work/CppQueryable

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Intall GTEST and GMOCK
      run: sudo apt-get install libgtest-dev && sudo apt-get install cmake && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp ./lib/*.a /usr/lib

    - run: echo "Starting Functional Tests"
    - uses: actions/checkout@v3
    - name: Build and Run Functional Tests
      run: make FuncTests
