name: Functional Tests

on:
  push:
    branches: [ "ActionTest" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # linux:

  #   runs-on: ubuntu-latest
  #   env: 
  #     PROJECTS_PATH: /home/runner/work/CppQueryable
  #     GTEST_BASE_DIR: /usr/src/gtest

  #   steps:
  #   - name: Intall GTEST and GMOCK
  #     run: sudo apt-get install libgtest-dev && sudo apt-get install cmake && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp ./lib/*.a /usr/lib

  #   - uses: actions/checkout@v3
  #   - name: Build and Run Functional Tests
  #     run: make FuncTests

  windows:
    runs-on: windows-latest
    env: 
      PROJECTS_PATH: D:/a/CppQueryable
      GTEST_BASE_DIR: D:/a/CppQueryable/Installs/googletest/googletest
    steps:

    # (not sure if this step is necessary since we're already in git hub)
    # - name: Set up MinGW
    #   uses: egor-tensin/setup-mingw@v2
    #   with:
    #     platform: x64
    
    - name: Install GTEST and GMOCK
      run: mkdir ./Installs && cd Installs && git clone https://github.com/google/googletest.git
      shell: bash
    
    - name: Display Installs Directory
      run: cd ./Installs/googletest && cmake CMakeLists.txt && cmake && ls -l ./googletest/src && ls -l ./googletest/include
      shell: bash

    - uses: actions/checkout@v3
    - name: Build and Run Functional Tests
      run: make FuncTests
      shell: bash