name: Functional Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo "Starting Functional Tests: ${{ github.event_name }}"
    - uses: actions/checkout@v3
    - name: Build and Run Functional Tests
      run: make FuncTests
