name: Functional Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECTS_PATH: /home/runner/work/CppQueryable

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo "Starting Functional Tests"
    - uses: actions/checkout@v3
    - name: Build and Run Functional Tests
      run: make FuncTests
